language: bash

services: 
  - docker

env:
  - DIR=magnolia-base/alpine
  - DIR=magnolia-base/slim
  - DIR=magnolia-ce
  - DIR=magnolia-ce-pgsql

script:
  - DIR=${DIR} && make build
      
deploy:
  provider: script
  script: 
    - DIR=${DIR} && make push
  on:
    branch: master

# vim:set et ts=2 sw=2: